# Generated by Django 5.0.6 on 2026-09-20 13:22

import detector.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, default='Anonymous', max_length=120)),
                ('image', models.ImageField(upload_to=detector.models.scan_upload_path)),
                ('predicted_class', models.CharField(choices=[('DR', 'Diabetic Retinopathy Detected'), ('No DR', 'No Diabetic Retinopathy')], max_length=20)),
                ('confidence', models.FloatField()),
                ('dr_probability', models.FloatField()),
                ('no_dr_probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
